services:
  tara:
    image: ghcr.io/tara-tool-thi/thiara:latest
    restart: always
    volumes:
      - ./tara:/app/Data
      - ./imprint.html:/app/wwwroot/imprint.html
    networks:
      - web
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1g"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tara.rule=Host(`tara.security.science`)"
      - "traefik.http.routers.tara.entrypoints=https"
      - "traefik.http.routers.tara.tls=true"
      - "traefik.http.routers.tara.tls.certresolver=le"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=DataSource=/app/Data/app.db;Cache=Shared

networks:
  web:
    external: true
